# run every 2 day (we dontneed it to be updated too fast
stages:
  - deploy

update_badge_codeberg:
  stage: deploy

  environment:
    name: update_badge_codeberg

  image: bitnami/git:latest

  variables:
    GIT_BOT_USERNAME: "favorite_music_badge_bot"
    GIT_HOST: "codeberg.org"
    CHANNEL_ID: "UCB3TKqt3XsvwZPeFw5skSjA"
    REPOSITORY: "https://codeberg.org/virtualfuzz/.profile"
    README_FILENAME: "README.md"

  script:
    # load ssh key
    - mkdir ~/.ssh
    - echo "$SSH_KEY" | base64 -d > ~/.ssh/gitlab-cicd
    - chmod 400 ~/.ssh/gitlab-cicd
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/gitlab-cicd

    # configure git
    - ssh-keyscan -t rsa "$GIT_HOST" >> ~/.ssh/known_hosts
    - git config --global user.email "$GIT_EMAIL_BOT"
    - git config --global user.name "$GIT_BOT_USERNAME"

    # install go
    - curl https://dl.google.com/go/go1.24.5.linux-amd64.tar.gz -o go1.24.5.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.24.5.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin:~/go/bin

    # get go program
    - go install codeberg.org/virtualfuzz/favorite_music_badge@v0.0.1
    - favorite_music_badge -repository "$REPOSITORY" -filename "$README_FILENAME" "$CHANNEL_ID"
